### ISSUE TITLE
Erubis deprecated in Rails 5.1

### ISSUE THREAD

**Issue by bknarendra** [indirect/haml-rails#121]
Template rendering moved to Erubi in Rails master, this generated a depreciation notice in the HAML gem:

`DEPRECATION WARNING: ActionView::Template::Handlers::Erubis is deprecated and will be removed from Rails 5.2. Switch to ActionView::Template::Handlers::ERB::Erubi instead.`

**Comment by mohitnatoo** [comment]
To add more context to the above description, the latest version of haml-rails seems to have dependency over haml version < 5.0.
We'd need to make use of haml 5.0 instead.

**Comment by sergiotapia** [comment]
+1

**Comment by k0kubun** [comment]
This is already resolved by https://github.com/indirect/haml-rails/pull/128 and https://github.com/haml/haml/commit/7577c187580b6b7a9fcd788c1d72b8894321334c. Use haml-rails 1.0 and haml 5.0.

And if you use :erb filter in Haml on Rails, you may want to use Haml 5.0.1 because of https://github.com/haml/haml/pull/914.

**Comment by syguer** [comment]
@k0kubun Thanks!

**Comment by marko-avlijas** [comment]
I am still getting this in rails 5.1.6. Do I need to change my Gemfile?
I used what's on rubygems.

    gem 'haml', '~> 4.0', '>= 4.0.7'
